# Generated by Django 4.0.3 on 2022-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=250)),
                ('merchant_code', models.CharField(max_length=250)),
                ('merchant_address', models.TextField()),
            ],
        ),
    ]
